In [4]:
import pandas as pd
import numpy as np

In [5]:
def neural(a_in, w, b):
    return a_in @ w + b

In [8]:
a = np.array([
    [1], [2],[3]
    ])

b = np.array([[1,2,3]])

In [11]:
print(np.matmul(a,b))

[[1 2 3]
 [2 4 6]
 [3 6 9]]
